version: 2

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X github.com/zlliang/chore/internal/buildinfo.Version={{.Version}}

archives:
  - formats: [tar.gz]

changelog:
  use: github
  sort: asc
  abbrev: -1
  filters:
    exclude:
      - "^docs:"
      - "^ci:"
  groups:
    - title: Features
      regexp: '^.*?feat'
      order: 0
    - title: Bug fixes
      regexp: '^.*?fix'
      order: 1
    - title: Others
      order: 999
